# Generated by Django 4.0.4 on 2022-05-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalmetadata',
            name='iswc',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
