# Generated by Django 4.0.4 on 2022-05-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_works', '0002_alter_musicalmetadata_iswc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalmetadata',
            name='iswc',
            field=models.CharField(max_length=50),
        ),
    ]
